Fix CI
Signed-off-by: zeramorphic <zeramorphic@proton.me>

diff --git a/.github/workflows/push_main.yml b/.github/workflows/push_main.yml
--- a/.github/workflows/push_main.yml
+++ b/.github/workflows/push_main.yml
@@ -21,6 +21,23 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: check case sensitivity
+        uses: credfeto/action-case-checker@v1.3.0
+
+      - name: look for ignored files
+        uses: credfeto/action-no-ignored-files@v1.1.0
+
+      - name: check for lean files with the executable bit set
+        shell: bash
+        run: |
+          executable_files="$(find . -name '*.lean' -type f \( -perm -u=x -o -perm -g=x -o -perm -o=x \))"
+          if [[ -n "$executable_files" ]]
+          then
+            echo "ERROR: The following Lean files have the executable bit set."
+            echo "$executable_files"
+            exit 1
+          fi
+
       - name: install elan
         run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:nightly-2023-08-15
 
@@ -91,47 +108,3 @@ jobs:
 
       - name: deploy website
         uses: actions/deploy-pages@v1
-
-  style_lint:
-    name: Lint style
-    runs-on: ubuntu-latest
-    steps:
-      - name: cleanup
-        run: |
-          find . -name . -o -prune -exec rm -rf -- {} +
-
-      - uses: actions/checkout@v4
-
-      - name: check case sensitivity
-        uses: credfeto/action-case-checker@v1.3.0
-
-      - name: look for ignored files
-        uses: credfeto/action-no-ignored-files@v1.1.0
-
-      - name: check for lean files with the executable bit set
-        shell: bash
-        run: |
-          executable_files="$(find . -name '*.lean' -type f \( -perm -u=x -o -perm -g=x -o -perm -o=x \))"
-          if [[ -n "$executable_files" ]]
-          then
-            echo "ERROR: The following Lean files have the executable bit set."
-            echo "$executable_files"
-            exit 1
-          fi
-
-      - name: install python
-        if: ${{ 'ubuntu-latest' == 'ubuntu-latest' }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: 3.8
-
-      - name: install elan
-        run: |
-          set -o pipefail
-          curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
-          ./elan-init -y --default-toolchain none
-          echo "$HOME/.elan/bin" >> "${GITHUB_PATH}"
-
-      - name: run style linters
-        run: |
-          lake exe lint-style
